### ISSUE TITLE
[client][server] GET request URL for customer to submit Search Criteria

### ISSUE THREAD

**Issue by blankmaker** [Reckless-Saturn/restaurant-app#23]
Opening issue for us to track. For @armandopmj and @phoenix16t : 

Have you guys thought about how the Customer can do a GET request to submit their Search Criteria of available restaurants? Armando: We talked about using a URL query string for this. Here's what I'm thinking as the GET request: 

```
var getSearchResults = function() {
  return $http({
  method: 'GET', 
  url: '/ArmandoAndEddieurl?find_cuisine=american&find_price=2&find_party=6&find_distance=0.5
})
.then(function(response) {
  return response.data
});
```

Here's a breakdown of the URL query string after the `?` mark: 

```
find_cuisine = american
find_price = 2 // or '$$', whichever you'd prefer
find_party = 6 // party size
find_distance = 0.5 // miles away. I believe you calculating this server-side? 
```

Right now, we're expecting an array of results. @lmle has hardcoded some data for us to work with for now. Let us know what you think

**Comment by blankmaker** [comment]
Here's how yelp does their query string (in case you need an example)

```
http://www.yelp.co.uk/search?find_desc=chinese&find_loc=Shoreditch%2C+London&ns=1#find_loc=53+Great+Eastern+St,+London&attrs=RestaurantsPriceRange2.2
```

**Comment by armandopmj** [comment]
@blankmaker  @lmle  @phoenix16t 
Hey guys, I believe that info will come in as text after the ? on the URL as we have discussed.  Me and Eddie will figure out how this is exactly handled (Complied and Sent) from the client side. Eddie will have a better idea regarding what data structures will be sent with.  @phoenix16t  Array or Object?

**Comment by blankmaker** [comment]
Yup - sounds good. Yeah I planned on it being after a ? mark. Just let us know what that URL string structure should be

As for the response, it should be an Json stringified object, with one of the properties containing an array (kind of like what the chatterbox server returned).

**Comment by blankmaker** [comment]
^ of course whenever you get to it. Just wanted to open the issue so we can track.

**Comment by armandopmj** [comment]
Awesome, I would expect the response to come back similar to chatterbox however, I'm not sure if Eddie had something else in mind.

**Comment by phoenix16t** [comment]
Hey, sorry guys. I'm a little behind today and playing catch-up. An object is perfect. I'll implement the following fields into my search criteria:
find_cuisine
find_price
find_distance 

I'm _not_ gonna implement "find_party" into the db search as that should be on the restaurant. @blankmaker , find_price=2 is perfect. We're leaving this in the db as a range from 1-5.

**Comment by lmle** [comment]
I made some edits to this; URL will look like:

'http://[URL-HERE]?find_distance='+distance+'&find_priceRange='+priceRange+'&find_partySize='+partySize+'&find_cuisine='+cuisine

Stay tuned for my pull request.

Search queries:
- find_distance
- find_priceRange
- find_partySize
- find_cuisine
