### ISSUE TITLE
[client] After submitting Search Criteria, it should redirect to 'search-results' page

### ISSUE THREAD

**Issue by blankmaker** [Reckless-Saturn/restaurant-app#25]
After PR https://github.com/Reckless-Saturn/restaurant-app/pull/24 , Submitting the form in `search-criteria.html` currently calls the function `getSearchResults`, which is housed in the `Customers` factory. 

At the moment, it is just console logging that it's doing a GET request until Issue: https://github.com/Reckless-Saturn/restaurant-app/issues/23 is finished . After the GET request, this form should also redirect the  the customer to `search-results` once the GET request is complete.

**Comment by lmle** [comment]
Handled by:
21e5bea
