### ISSUE TITLE
[db] 'available' field for restaurants has to be true or false

### ISSUE THREAD

**Issue by lmle** [Reckless-Saturn/restaurant-app#26]
When toggling with ion-toggle, it returns 'true' or 'false'. So, db must be changed to receive 'true' or 'false for the 'available' field, instead of 0 or 1.

**Comment by phoenix16t** [comment]
Not a problem. The "available" field in the db should remain the same, but
I'll modify the query results to return true or false

**Comment by lmle** [comment]
Okay, thanks @phoenix16t :)
