### ISSUE TITLE
[client] Send server customer's location; send server restaurant's location

### ISSUE THREAD

**Issue by lmle** [Reckless-Saturn/restaurant-app#30]
Add 'customerLoc' in searchUrl in services.js

**Comment by lmle** [comment]
Note: http://ngcordova.com/ -- check out 'geolocation'

**Comment by lmle** [comment]
Customer's lat and long handled by 9b035ba.

**Comment by phoenix16t** [comment]
hey mai, is it possible to use this to find the location of new restaurants as they're being added?

**Comment by lmle** [comment]
@phoenix16t Do you mean send the server the restaurant's location based on the address they provide?

**Comment by phoenix16t** [comment]
yea. is it easier to find them through the frontend, then just pass the latitude and longitude along the post request?

**Comment by lmle** [comment]
Note to self: check [this](http://stackoverflow.com/questions/5984179/javascript-geocoding-from-address-to-latitude-and-longitude-numbers-not-working) and [this](http://aspsnippets.com/Articles/Google-Maps-API-V3-Get-Latitude-and-Longitude-of-a-location-from-Address-using-JavaScript.aspx) out; old, though.

**Comment by lmle** [comment]
Restaurant's lat and long sent from client to server handled by 058a9ba.
