### ISSUE TITLE
[client][server] Handle log-ins

### ISSUE THREAD

**Issue by lmle** [Reckless-Saturn/restaurant-app#45]

**Comment by blankmaker** [comment]
We're going to create an extra login button on the splash page for our own 'homegrown' signup flow. Based on username, we'll be able to determine whether or not they're a customer or restaurant. Working on this today

**Comment by blankmaker** [comment]
Just did a PR, which @armandopmj merged in https://github.com/Reckless-Saturn/restaurant-app/pull/56

Keeping this issue open since I didn't add logic to push user to the appropriate path based on their customer type.

**Comment by blankmaker** [comment]
Note to self: this is changing to a 'GET' request. Make sure to add a URL query string for the username. also add username for restaurants.

**Comment by lmle** [comment]
Handled by 278965329f9d0db8a6b5d073141a44cc8d582bf0, but needs to be verified with server with SQL running @phoenix16t @armandopmj

**Comment by armandopmj** [comment]
@lmle 
Where you able to test the login using the sendResponse function in request handlers?

**Comment by blankmaker** [comment]
hey @armandopmj - we were able to. Mai was able to get the user to go down the correct path based on their user type. On the front-end side, we're pretty much done with the app and are just working on tests and documentation.

Is there anything you guys need to finish up as well?

**Comment by armandopmj** [comment]
@lmle @phoenix16t @blankmaker 
Hey David, Eddie and me are also working on testing and documentation.  I will also be doing a run through of the app on my phone and a test with sql.
