### ISSUE TITLE
[client] Sign-up validation

### ISSUE THREAD

**Issue by phoenix16t** [Reckless-Saturn/restaurant-app#47]
Need to validate all fields. They should all contain _some_ data
Need to validate the email and phone fields for formatting

**Comment by blankmaker** [comment]
Hey Eddie-- we can validate this on the front end, I think. Would that help? I think HTML 5 has some built in form validation

**Comment by phoenix16t** [comment]
good point - probably better to validate before the request even hits the
server. at the moment, there's no validation whatsoever. the diner can hit
submit without entering any data, and the user account will still be added
successfully

**Comment by blankmaker** [comment]
Okay - just looked into this. This is def possible on the client-side, but the HTML5 version of validation is kind of shitty (there's no message for the user to tell them that they their inputs aren't valid). 

I'm customizing the angular version for Ionic - will submit a PR for ya later today.

For reference: http://www.ng-newsletter.com/posts/validations.html

**Comment by blankmaker** [comment]
Finished. Submitted a PR: https://github.com/Reckless-Saturn/restaurant-app/pull/66

@lmle can you review? There were some merge conflicts with the styling ,but I think I resolved most.
