### ISSUE TITLE
App name!

### ISSUE THREAD

**Issue by lmle** [Reckless-Saturn/restaurant-app#64]
Let's brainstorm ideas here.

**Comment by armandopmj** [comment]
No one brain stormed...

**Comment by armandopmj** [comment]
I like the name you went with Mai

**Comment by lmle** [comment]
haha, yep @armandopmj I guess we'll use Famished

**Comment by blankmaker** [comment]
yay! i'm cool with it too

**Comment by phoenix16t** [comment]
ditto

**Comment by blankmaker** [comment]
Famished, it is. Closing!
